# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hudson Yuen
tagline:          'A Jekyll theme'
description:      'Computer Science & Statistics Student'
url:              'https://hudsonyuen.com'
baseurl:          '/'

author:
  name:           'Hudson Yuen'
  url:            https://hudsonyuen.com

plugins:
  - jekyll-paginate
  - jekyll-gist

paginate:         4
paginate_path:    "/blog/page:num/"

# Custom vars
version:          v1.0 Feb 2020

github:
  repo:           https://github.com/poole/hyde